# Lec04: Numpy

In [4]:
import numpy as np
# # python에서 잘못된 변수 선언(데이터 타입을 지정함)
# int a = 2
# python에서 올바른 변수 선언
a = 2

In [5]:
# 배열 생성
A = np.array([[1,2], [3,4]])
# 행렬 생성
B = np.matrix([[1,2],[3,4]])

In [49]:
matB = np.array([[3,1,9],[2,5,8],[4,7,6]]) # 리스트로 ndarray를 생성
matC = np.array(((3,1,9),(2,5,8),(4,7,6))) # 튜플로 ndarray를 생성

matB == matC

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [14]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [16]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [27]:
# start로 지정한 값부터 stop 사이 값 중 step 간격을 갖는 수열을 생성한다
#arange([start,] stop[, step,][, dtype])

In [20]:
# range로 생성
for i in range(10,20,2):
    print(i)

10
12
14
16
18


In [21]:
# np.arange()로 생성
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [28]:
# dtype 객체로 지정
dt = np.dtype('float')

# ndarray를 생성할 때 dtype으로 지정(dtype 객체 사용)
x = np.array([1.1, 2.1, 3.1], dtype=dt)

# ndarray를 생성할 때 dtype으로 지정(직접 문자열로 지정)
x = np.array([1.1, 2.1, 3.1], dtype='float')

In [29]:
matB = np.array([[3,1,9],[2,5,8],[4,7,6]])

# ndarray의 크기를 반환
matB.shape

(3, 3)

In [30]:
matB.shape?

In [31]:
A = np.array([[-2,1],[1.5,-0.5]])

# ‘linalg’는 선형대수를 위한 모듈
# A의 역행렬 계산
np.linalg.inv(A)

array([[ 1.,  2.],
       [ 3.,  4.]])

In [32]:
# A의 행렬식 계산
np.linalg.det(A)

-0.5

In [33]:
# A의 랭크를 계산
np.linalg.matrix_rank(A)

2

In [34]:
# 벡터 a, b 정의
a, b = np.array([2,-4,1]), np.array([3,1,-2])

# 벡터 a, b의 내적(scalar product)
np.inner(a,b)

0

In [35]:
# 벡터 a, b의 외적(cross product)
np.cross(a,b)

array([ 7,  7, 14])

In [36]:
x2d = np.arange(12).reshape(3,4)

# x2d의 내용 확인
x2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# 두번째줄의 두번째 요소부터 전부 꺼낸다
a = x2d[1][1:]

# a의 내용 확인
a

array([5, 6, 7])

In [38]:
# a의 일부 요소를 변환
a[0] = -1

# a는 뷰였으므로 x2d에도 변경의 영향이 미친다
x2d

array([[ 0,  1,  2,  3],
       [ 4, -1,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
# ndarray고유의 방법을 사용
b = x2d[1:, 2:]; b

array([[ 6,  7],
       [10, 11]])

In [40]:
# 파이썬의 기본 리스트를 대상으로 위와 같이 슬라이싱하면 오류가 발생한다
k = [[1,2,3],[4,5,6]]

k[1,:]

TypeError: list indices must be integers or slices, not tuple

In [41]:
b[:, :]=20

#b는 뷰이므로 위에서 변경한 결과가 x2d에도 반영된다
x2d

array([[ 0,  1,  2,  3],
       [ 4, -1, 20, 20],
       [ 8,  9, 20, 20]])

In [42]:
### 부울(bool)값 인덱싱의 예
# 난수 값을 생성한다
dat = np.random.rand(2,3); dat

array([[ 0.21545525,  0.99886442,  0.5285991 ],
       [ 0.51982544,  0.05936085,  0.53182711]])

In [43]:
# 기준 0.5 값을 넘는 부울 값 배열을 만든다
bmask = dat > 0.5; bmask

array([[False,  True,  True],
       [ True, False,  True]], dtype=bool)

In [44]:
# ndarray dat에 대해 부울 값 배열로 인덱싱한다
highd = dat[bmask]; highd

array([ 0.99886442,  0.5285991 ,  0.51982544,  0.53182711])

In [45]:
# highd의 일부를 변경한다
highd[0] = 10; highd

array([ 10.        ,   0.5285991 ,   0.51982544,   0.53182711])

In [46]:
# 위에서 highd를 변경했지만 dat에는 반영되지 않았다.  highd는 dat의 사본
dat

array([[ 0.21545525,  0.99886442,  0.5285991 ],
       [ 0.51982544,  0.05936085,  0.53182711]])

In [47]:
# 1차원 ndarray
nda = np.arange(10); nda

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# 앞서 설명했던 기본 인덱싱의 방법(슬라이싱)으로 ndb라는 뷰를 만든다
ndb = nda[1:4]

# 정수 배열 인덱싱으로 ndc라는 사본을 만든다 (리스트의 형태로 인덱스를 넘긴다)
ndc = nda[[1,2,3]]

# ndb와 ndc는 그 내용이 같다
ndb == ndc

### ndb와 ndc는 같은 값을 갖고 있지만 ndc는 사본이므로 일부 요소의 값을 변경해도 
# 원래 배열 nda에 영향을 미치지 못한다

array([ True,  True,  True], dtype=bool)

In [52]:
# 2차원 3x4 ndarray
nda = np.arange(12).reshape((3,4)); nda

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
### 여러 개의 배열을 사용한 인덱싱의 예
# 위치 (0,2), (2,0), (1,3)의 값을 꺼낸다
ndb = nda[[0,2,1], [2,0,3]]; ndb

array([2, 8, 7])

In [54]:
### 특정 행과 열이 교차하는 자리에 위치한 요소를 꺼낼 때는 np.ix_ 함수를 사용한다
# (0,2)행과, (1,3)열이 교차하는 요소를 꺼낸다
nda[np.ix_([0,2], [1,3])]

array([[ 1,  3],
       [ 9, 11]])

In [56]:
# b = a  (a는 ndarray일 때)
# b = a[:]  (b = a와 같다)
# b = a[1:]  (a의 부분 배열)
# b = a.reshape((3,2))  (reshape 메서드)
# b = np.reshape(a, (3,2))  (reshape 함수)
# b = np.array(a, copy=false)  (copy=false이므로 뷰가 생성)

# b = a[a > 10]  (부울 값에 의한 응용 인덱싱)
# b = a[[1,2,4]]  (정수 배열에 의한 응용 인덱싱)
# b = a[np.ix_([0,2], [3,4])  (ix_함수에 의한 응용 인덱싱)
# b = a.copy()  (복사 메서드)
# b = np.copy(a) (복사 함수)
# b = a.flatten()  (flatten 메서드)

In [58]:
# Fortran과 같은 방식으로 열방향 우선 메모리 배치 지정
nda = np.arange(12).reshape(4,3,order='F')

# C와 같이 행방향 우선 메모리 배치 지정
ndb = np.zeros((3,3), order = 'C')

In [59]:
# 2x6 ndarray를 만든다
nda = np.arange(12).reshape(2,6)

nda

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [60]:
# nda에 ufunc(square)를 적용하여 각 요소를 제곱한다
np.square(nda)

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]], dtype=int32)

In [62]:
# 1x3 ndarray
nda = np.array([1,2,3])

# 1x3 ndarray에 스칼라 1을 더한다
nda + 1

array([2, 3, 4])

In [63]:
nda = np.arange(24).reshape(4,3,2)

ndb = np.arange(6).reshape(3,2)

ndc = np.arange(3).reshape(3,1)

# 이 연산은 브로드캐스팅으로 수행이 가능하다
nda+ndb-ndc

array([[[ 0,  2],
        [ 3,  5],
        [ 6,  8]],

       [[ 6,  8],
        [ 9, 11],
        [12, 14]],

       [[12, 14],
        [15, 17],
        [18, 20]],

       [[18, 20],
        [21, 23],
        [24, 26]]])

In [64]:
nda = np.arange(12).reshape(3,4)

# 크기 (4, )인 배열.   크기가 (4,1)이 아니란 것에 유의!
ndb = np.arange(4)

# 브로드캐스팅으로 계산 가능
nda + ndb

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [65]:
ndb = np.arange(4).reshape(4,1)

# 오류 발생
nda + ndb

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [66]:
nda = np.arange(12).reshape(4,3)

ndb = np.arange(4).reshape(4,1)

nda+ndb

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [67]:
ndb=np.arange(4)

#오류가 발생한다
nda+ndb

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

#### EXERCISE

In [68]:
# 1.0부터 8까지의 값을 순차적으로 갖는 3x3 행렬을 생성하시오
z = np.arange(9).reshape(3,3)

print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [69]:
# 2. i번째 열은 원소값으로 모두 (i-1)을 갖는 5x5 행렬을 생성하시오
z = np.zeros((5,5))
z += np.arange(5)

z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [70]:
# 3.integer(32 bit) ndarray를 float(32 bit) ndarray로 바꾸려면 어떻게 해야하는가?
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
z = np.array(z,dtype=np.float32)
z = np.asarray(z, dtype=np.float32)

z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.], dtype=float32)